### PR TITLE
Implement image capturing for spatialite data

### PR DESCRIPTION
**Pull request by dispiste**
Implement picture capturing and storage for spatialite data. A new button is added on the FeaturePagerActivity to access the images associated with a record. There, we can take new pictures and remove or view existing ones.

An auxiliary table is created on the spatialite database ("geopap_resources"), which stores the images as blob. The table is prepared to store other kind of resources (for instance videos), which can be stored as blobs or as external resources. Currently, only images are exposed in the user interface, using the blob storage. The table includes a field to store a thumbnail (also using blob type), representing the resource as a low resolution image.

Note that process of writing to the database is NOT using an AsyncTask, as I was getting some errors when using AsyncTask.

### CODE REVIEW

**Comment by moovida** [comment]
Hi @dispiste , thanks a ton for all this. I more or less went over this request and it looks great to me. One of the things that looks a bit strange to me, is that the icon is black, whereas the other icons are all white. Also you used a png format, while it is now possible to use fantastic xml vector icons based on svg paths.
I attach you here the two icons you need, so later, when we meet, we can insert them.
Also we will need to talk about the translation part.



[vector_icons.zip](https://github.com/geopaparazzi/geopaparazzi/files/626638/vector_icons.zip)

**Comment by dispiste** [comment]
Hi Andrea, I replaced the pngs by the vector images as requested. You also mentioned something about translations, but I don' know exactly what you expect on this area.

**Comment by moovida** [comment]
Hi @dispiste , true, the problem is that you translated the strings in the xml files. Instead we are using transifex for the translations. So before a release I pull the translations from the site, which overwrites the translation files: https://www.transifex.com/moovida/geopaparazzi/

So you would have to copy the translations to Spanish into transifex to get them in the next release.

**Comment by dispiste** [comment]
Great, I'll copy the translations to transifex

**Comment by moovida** [comment]
Please give me full Friday to merge the request and push the English file to transifex. Then you are good to go. The

**Pull request merged**
