### PR TITLE
Big Geopaparazzi upgrade

### PR DESCRIPTION
**Pull request by moovida**
This is the huge upgrade to geopaparazzi 5 to support android 6 with complete review of the user interface.
Also many features were added.

### CODE REVIEW

**Comment by mj10777** [comment]
My first attempt to install this failed
* after updating the sdk to `Android 6 API 23 with Build Tools revision 23.0.2`
   * which is reported during the `./gradlew clean`
* the following error still occurs during `./gradlew clean`:
   * `Cannot evaluate module wms_nww : Configuration with name 'default' not found.`

**Comment by moovida** [comment]
Hi @mj10777 , you need to have this project checked out:
https://github.com/geopaparazzi/wms_nww

it should be in the same folder as the geopaparazzi repository, so that from within it, it is accessible as: 
```
../wms_nww
```

**Comment by mj10777** [comment]
After:
* `git clone git@github.com:geopaparazzi/wms_nww` under the  `geopaparazzi` directory
   * both `./gradlew clean` and `./gradlew assemble` 
      * ran correctly

I will try this out tomorrow, but I assume I will have to update my android system to Android 6.0
* still am using 4.4.2

**Comment by moovida** [comment]
The minimum version on the device should be 4.3 (or 4.4, right now I don't remember), so you should be ok.

**Comment by mj10777** [comment]
Encouraged by this, I tried it
* needed root to install the created GeoPaparazzi_5.0.0.apk
   * and the Application starts

Will have to figure how the new system works
* I assume create a project somewhere
   * and configure it (.i.e where to find the Map-Databases)

**Comment by moovida** [comment]
The project creation works as usual.

The thing that changed is that it doesn't load all maps and databases at startup. From the tilesview (first icon on actionbar) you have a plus button that allows you to browse the device and add the selected map.

**Comment by mj10777** [comment]
OK, I have gotten that far
* but could not load a mbtiles file and no idea how to load the geometries (Table and View are active)
   * and each time have to maneuver back to the maps directory

**Comment by mj10777** [comment]
Reading the blogpost
* the images are different from what I see
* icons are black in the action bar (white) and black on the file list (green in image)
* the context menu shown has a 'select tile sorce' and 'create new project', mine does not (maybe due to the german?)

**Comment by moovida** [comment]
Hi @mj10777 , sorry for the late reply.

* the black images are due to an older version compatibility, it is a bit sad, but it is just a problem of cosmetics
* if you are looking at it in landscape mode and maybe on a tablet, then the missing entries should be visible on the action bar as icons. If there is space, the items are placed on the action bar

**Pull request merged**
