### PR TITLE
add accuracy to gpsInfoDialogFragm

### PR DESCRIPTION
**Pull request by tghoward**
I thought it would be nice to have gps accuracy in the info dialog. I hope you agree!  Only thing I'm not sure about is whether units are always in meters.

### CODE REVIEW

**Comment by tghoward** [comment]
I forgot to mention: tested on Android 4.4.2 and Android 6.0.1 and seems fine on both.

**Comment by moovida** [comment]
That looks good to me Tim, thanks for bringing this in. The accuracy is indeed in meters (i.e it is not the hdop), which makes it more readable to users.

I will merge this is as soon as I work on the code, so that I also remember to extract the strings for translation.

**Comment by tghoward** [comment]
Thanks Andrea - sorry I didn't see that you had already extracted all the other strings there - Android Studio was hiding that the strings were coming from elsewhere. At least I wasn't seeing what it was trying to tell me!

**Comment by moovida** [comment]
No problem, it has been a quick one :-)

**Pull request merged**
