### PR TITLE
File view

### PR DESCRIPTION
**Pull request by brentfraser**
This pull request slightly expands the Feature linking system to allow viewing of PDF files as blobs in a  Spatialite database.

It relaxes the the database query to get BLOB_PDF (as well as BLOB_IMAGE).
It changes the Feature display on a select-for-view to be read-only=false so the linked-files button shows up.

These changes are simply to get people using Feature linking and see if there is enough interest to do more.

Under the current set of objects, adding code to allow EXTERNAL file links and other file types will require the replication a lot of code and generally make the code more complex.  The better solution would be to refactor the objects to simply have a Resource object with a few more properties to eventual issue an intent to Android to display the file.

### CODE REVIEW

**Comment by brentfraser** [comment]
issue #454

**Comment by moovida** [comment]
I will leave this review to @dispiste :-) Thank you

**Comment by dispiste** [comment]
Hi @brentfraser, your PR contains valuable additions, but it contained some problems:
- it was possible to save records and add images even when a feature was selected using the info tool (read-only mode)
- some texts were modified (Image -> Document) but the resource key was not changed

I've created a new pull request, based on yours, which corrects these issues and also provides additional improvements:
- if a mimetype is found in the type field, it is used to launch the intent. This opens the door to store any kind of resource in the database. Note that the old behavior is still supported and it is still used to store images (i.e. images are stored using the 'BLOB_IMAGE' literal in the type field).
- the resource browser now shows both external and blob resources, if they are present. Note that the thumbnail is still expected to be stored as a blob.

Regarding external resources, I've done a basic test and it works for me. Resource paths are expected to be relative to the "imageSaveFolder" path, which is calculated using the following code:
imageSaveFolder = new File(ResourcesManager.getInstance(this).getApplicationSupporterDir(), "sqlite_res");

On my installation, this becomes the "geopaparazzi/sqlite_res" folder. Since nobody is using this for the moment, this path could be changed if needed (because the changes mentioned by Andrea on the last version of Android, whose details I don't remember exactly).

**Comment by dispiste** [comment]
I forgot to mention that the new PR is https://github.com/geopaparazzi/geopaparazzi/pull/469

**Pull request merged**
