### PR TITLE
Boost Notes buttons size, allow mixed case formname (button text)

### PR DESCRIPTION
**Pull request by brentfraser**
#427

### CODE REVIEW

**Comment by moovida** [comment]
Hi @brentfraser , thanks for this. Funny enough today I gave a look at the code to answer to your opened issue. 
My wish was to put a scale factor in the preferences and then make some of the views answer to it.
The thing that stopped me is the fact that the grid is hardcoded to have 1 column. This would be a poor choice for tablets in case for many forms, don't you think?

Any idea on how to make this consistent?

**Comment by brentfraser** [comment]
We could try to calculate it programmatically, but I think there are too many possibilities (from a watch to a large tablet, portrait/landscape, etc).  So I think adding a grid columns to preferences as well as a text scale factor is a great solution.

**Comment by brentfraser** [comment]
I'm working on adding the text scale and grid columns to Preferences.  I've added a few strings to string.xml.  Do I need to do a translation to the other languages (with their own string.xml files) before doing a pull request?

**Comment by moovida** [comment]
Hi @brentfraser , in the end I decided to keep these preferences in the menu of the addnotesactivity. The main preferences seemed too far for me and difficult to explain as generic.

So I took part of your code (thanks) and added the necessary parts. For these reason I will close this PR here.

**Comment by brentfraser** [comment]
I think that is OK.  I had anticipated using the scale factor for other GUI components as well (and maybe the street names on the vector maps), but we can do that as a separate task later.

**Comment by brentfraser** [comment]
Did you commit your preferences.xml?

**Comment by brentfraser** [comment]
Ignore the above comment.  I'm having problems merging.

**Comment by moovida** [comment]
```
I think that is OK. I had anticipated using the scale factor for other GUI components as well (and maybe the street names on the vector maps), but we can do that as a separate task later.
```
I understand and agree. But the column number doesn't fit in there, it is specific to the "add notes" layout. 
And we should move also scalefactor to general preference only when it is clear what it does. Right now one might have changed it and not see any change, since it only applies to a view.

**Comment by moovida** [comment]
Not sure what you mean. This is now all in the contect menu of the notes view. No preferences involved.

**Comment by brentfraser** [comment]
Have a look at the four calls to preferences.getInt at:

https://github.com/geopaparazzi/geopaparazzi/blob/60bcfea317e83c6e229a527aa729baf877447dbe/geopaparazzi_core/src/main/java/eu/geopaparazzi/core/ui/activities/AddNotesActivity.java#L243

https://github.com/geopaparazzi/geopaparazzi/blob/60bcfea317e83c6e229a527aa729baf877447dbe/geopaparazzi_core/src/main/java/eu/geopaparazzi/core/ui/activities/AddNotesActivity.java#L249

https://github.com/geopaparazzi/geopaparazzi/blob/60bcfea317e83c6e229a527aa729baf877447dbe/geopaparazzi_core/src/main/java/eu/geopaparazzi/core/ui/dialogs/AddNoteLayoutDialogFragment.java#L75

https://github.com/geopaparazzi/geopaparazzi/blob/60bcfea317e83c6e229a527aa729baf877447dbe/geopaparazzi_core/src/main/java/eu/geopaparazzi/core/ui/dialogs/AddNoteLayoutDialogFragment.java#L77

**Comment by moovida** [comment]
These are the calls to the prefernces store, where the prefs of the layout are kept. But there is no preferences page in the general preferences. The "preferences page" of this is now in the Layout entry of the notes view menu.
Or maybe I am not understanding what you mean.

**Comment by brentfraser** [comment]
The location of the settings in the GUI is fine, but they are not persisted in the preferences system in the preferences.xml file so they are not saved between sessions. We need to add entries in the preferences.xml file for them.  Until we do that, GP will crash at the calls I listed above.

**Comment by brentfraser** [comment]
For some reason it now works.  Sorry for the noise.
And for anyone reading this, after doing some reading on the Android APIs, I see that the Preferences API is for PRESENTING settings in the GUI, while SharedPreferences is for PERSISTING the values between runs (or something like that).

**Comment by moovida** [comment]
Good to hear it works. And yes, it is as you say.

**Pull request closed without merging**
